name: Legacy smoke tests
inputs:
  script:
    description: 'The script to run. Pick from headless or heroku. Defaults to headless (pointing to localhost:300[0|9])'
    required: true
    default: 'headless'
  working-directory:
    description: 'the directory you wish you install the smoke tests to'
    required: false
    default: 'smoke'

description:
  Runs the legacy suite of smoke tests for xgovformbuilder/digital-form-builder
runs:
  using: composite
  steps:
    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: xgovformbuilder/digital-form-builder-legacy-smoke-tests
        path: ${{inputs.working-directory}}
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: |
        cd ${{inputs.working-directory}}
        yarn
        yarn run test:${{inputs.script}}
      shell: bash
    - name: "Tar files"
      if: ${{ success() || failure() }}
      shell: bash
      run: tar -cvf ${{inputs.working-directory}}/smoke-tests.tar reports
    - uses: actions/upload-artifact@v2
      if: ${{ success() || failure() }}
      with:
        name: smoke-tests
        path: smoke-tests.tar
        retention-days: 14

    - name: Run pa11y
      shell: bash
      run: yarn dlx pa11y-ci
