name: Branch QA
inputs:
  script:
    description: 'The script to run. Pick from headless or heroku. Defaults to headless (pointing to localhost:300[0|9])'
    required: true
    default: 'headless'

description:
  Runs the legacy suite of smoke tests for xgovformbuilder/digital-form-builder
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: xgovformbuilder/digital-form-builder-legacy-smoke-tests
        path: smoke
    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: smoke/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('smoke/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: |
        cd smoke
        node -v
        yarn
        yarn run test:${{inputs.script}}
      shell: bash
    - run: |
        ls
        ls -lah reports/
      shell: bash
    - name: "Tar files"
      if: ${{ success() || failure() }}
      shell: bash
      run: tar -cvf smoke-tests.tar reports
    - uses: actions/upload-artifact@v2
      if: ${{ success() || failure() }}
      with:
        name: smoke-tests
        path: smoke-tests.tar
        retention-days: 14
