name: Branch QA
inputs:
  name:
    description: 'The script to run. Pick from headless or heroku. Defaults to headless.'
    required: true
    default: 'headless'

description:
  Runs the legacy suite of smoke tests for xgovformbuilder/digital-form-builder
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      with:
        path: node_modules
    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: |
        cat package.json
        yarn
        yarn run test:headless
        ls -lah smoke-tests/designer/reports/
      shell: bash
    - name: "Tar files"
      if: ${{ success() || failure() }}
      shell: bash
      run: tar -cvf smoke-tests.tar smoke-tests/designer/reports
    - uses: actions/upload-artifact@v2
      if: ${{ success() || failure() }}
      with:
        name: smoke-tests
        path: smoke-tests.tar
        retention-days: 14
