name: Branch QA
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/README.md'
  workflow_dispatch:
jobs:

  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
        run: |
          yarn smoke-tests/designer smoke-test-headless
          ls -lah smoke-tests/designer/reports/
      - name: "Tar files"
        if: ${{ success() || failure() }}
        run: tar -cvf smoke-tests.tar smoke-tests/designer/reports
      - uses: actions/upload-artifact@v2
        if: ${{ success() || failure() }}
        with:
          name: smoke-tests
          path: smoke-tests.tar
          retention-days: 14
