name: Branch QA
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'The script to run. Pick from headless or heroku. Defaults to headless.'
        required: true
        default: 'headless'
jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
        run: |
          yarn test:headless
          ls -lah smoke-tests/designer/reports/
      - name: "Tar files"
        if: ${{ success() || failure() }}
        run: tar -cvf smoke-tests.tar smoke-tests/designer/reports
      - uses: actions/upload-artifact@v2
        if: ${{ success() || failure() }}
        with:
          name: smoke-tests
          path: smoke-tests.tar
          retention-days: 14
